// Data: products, categories, copy
const PRODUCTS = [
  // Beer
  { id: 'p01', cat: 'beer', style: 'IPA',    name: 'Хмільний Бунтар',     abv: 6.8, ibu: 65, price: 145, vol: '0.33 л', color: '#D89B3C', tagline: 'Сухий хміль. Жодних компромісів.',
    notes: 'Цитрусова гіркота, смола сосни, легка ноти грейпфрута.', pair: 'Смажене мʼясо, гострі сири.', origin: 'Крафтова пивоварня',
    image: 'https://plus.unsplash.com/premium_photo-1695285406175-c3b866e96091?auto=format&fit=crop&w=400&q=80' },
  { id: 'p02', cat: 'beer', style: 'Stout',  name: 'Чорна Кава о 4:00',   abv: 8.2, ibu: 42, price: 180, vol: '0.5 л',  color: '#2A1E16', tagline: 'Імперський стаут на холодній каві.',
    notes: 'Арабіка, темний шоколад, карамель, диму від солоду.', pair: 'Десерти, витримані сири.', origin: 'Крафтова пивоварня',
    image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=400&q=80' },
  { id: 'p03', cat: 'beer', style: 'Lager',  name: 'Тихий Ранок',         abv: 4.5, ibu: 22, price: 95,  vol: '0.5 л',  color: '#E8B766', tagline: 'Чистий лагер для буднів.',
    notes: 'Свіжий хліб, мед, тонка травʼяна нота.', pair: 'Риба, курка, салати.', origin: 'Крафтова пивоварня',
    image: 'https://images.unsplash.com/photo-1566633806327-68e152aaf26d?auto=format&fit=crop&w=400&q=80' },
  { id: 'p04', cat: 'beer', style: 'Wheat',  name: 'Пшеничний Полудень',  abv: 5.1, ibu: 14, price: 110, vol: '0.5 л',  color: '#F1CE7A', tagline: 'Нефільтроване. Мутне. Справжнє.',
    notes: 'Банан, гвоздика, цедра лимона.', pair: 'Літні салати, устриці.', origin: 'Крафтова пивоварня',
    image: 'https://images.unsplash.com/photo-1615332579037-3c44b3660b53?auto=format&fit=crop&w=400&q=80' },
  { id: 'p05', cat: 'beer', style: 'Sour',   name: 'Вишневий Шторм',      abv: 5.4, ibu: 8,  price: 165, vol: '0.33 л', color: '#B84544', tagline: 'Дика ферментація. Три місяці у дубі.',
    notes: 'Стигла вишня, кисломолочна свіжість, танін.', pair: 'Качка, тверді сири.', origin: 'Крафтова пивоварня',
    image: 'https://plus.unsplash.com/premium_photo-1695285406062-6d33b6ab539c?auto=format&fit=crop&w=400&q=80' },
  { id: 'p06', cat: 'beer', style: 'Porter', name: 'Димний Пілігрим',     abv: 7.0, ibu: 38, price: 155, vol: '0.5 л',  color: '#3A261A', tagline: 'Копчений солод з Карпат.',
    notes: 'Дим буку, какао, чорнослив.', pair: 'Барбекю, ковбаси.', origin: 'Крафтова пивоварня',
    image: 'https://images.unsplash.com/photo-1516458464372-eea4ab222b31?auto=format&fit=crop&w=400&q=80' },
  { id: 'p07', cat: 'beer', style: 'IPA',    name: 'Туманний Схід',       abv: 6.2, ibu: 45, price: 160, vol: '0.33 л', color: '#C9B98A', tagline: 'Hazy IPA, повний соку.',
    notes: 'Манго, маракуя, персик, мʼяка гіркота.', pair: 'Тайська кухня, суші.', origin: 'Крафтова пивоварня',
    image: 'https://images.unsplash.com/photo-1630446070374-df1ec648ac65?auto=format&fit=crop&w=400&q=80' },
  { id: 'p08', cat: 'beer', style: 'Lager',  name: 'Старий Млин',         abv: 4.8, ibu: 28, price: 105, vol: '0.5 л',  color: '#D5A24B', tagline: 'Віденський лагер за рецептом 1897 року.',
    notes: 'Тостований солод, карамель, сухий фініш.', pair: 'Шніцель, картопля.', origin: 'Крафтова пивоварня',
    image: 'https://images.unsplash.com/photo-1546622891-02c72c1537b6?auto=format&fit=crop&w=400&q=80' },
  { id: 'p09', cat: 'beer', style: 'Stout',  name: 'Нічний Караван',      abv: 9.1, ibu: 50, price: 210, vol: '0.33 л', color: '#1E1410', tagline: 'Імперіал Стаут у бочці з-під бурбону.',
    notes: 'Ваніль, дуб, каву, темні ягоди.', pair: 'Шоколадний десерт.', origin: 'Крафтова пивоварня',
    image: 'https://plus.unsplash.com/premium_photo-1695658863900-57ed9d7865be?auto=format&fit=crop&w=400&q=80' },
  { id: 'p10', cat: 'beer', style: 'Wheat',  name: 'Літній Сад',          abv: 4.9, ibu: 12, price: 115, vol: '0.5 л',  color: '#EFD890', tagline: 'Вайцен з цедрою бергамоту.',
    notes: 'Мед, бергамот, біла квітка.', pair: 'Сирна дошка, салати.', origin: 'Крафтова пивоварня',
    image: 'https://images.unsplash.com/photo-1462664450306-25ad625a342b?auto=format&fit=crop&w=400&q=80' },
  { id: 'p11', cat: 'beer', style: 'Sour',   name: 'Абрикосовий Бриз',    abv: 4.2, ibu: 6,  price: 150, vol: '0.33 л', color: '#E9A25E', tagline: 'Берлінер-вайсе з абрикосом.',
    notes: 'Абрикос, лимонна кислинка, свіжість.', pair: 'Легкі салати, сири.', origin: 'Крафтова пивоварня',
    image: 'https://images.unsplash.com/photo-1595600566063-2863388012be?auto=format&fit=crop&w=400&q=80' },
  { id: 'p12', cat: 'beer', style: 'IPA',    name: 'Сталевий Ранок',      abv: 7.5, ibu: 80, price: 170, vol: '0.33 л', color: '#B57A2C', tagline: 'Double IPA. Для тих, хто серйозно.',
    notes: 'Смола, манго, квіти хмелю, тривалий післясмак.', pair: 'Блакитні сири, гостре мʼясо.', origin: 'Крафтова пивоварня',
    image: 'https://images.unsplash.com/photo-1584225065152-4a1454aa3d4e?auto=format&fit=crop&w=400&q=80' },
  { id: 'p13', cat: 'beer', style: 'Porter', name: 'Залізний Кінь',       abv: 6.3, ibu: 34, price: 140, vol: '0.5 л',  color: '#2E1E14', tagline: 'Класичний лондонський портер.',
    notes: 'Шоколад, горіх, тостований хліб.', pair: 'Стейк, бургер.', origin: 'Крафтова пивоварня',
    image: 'https://plus.unsplash.com/premium_photo-1695558758852-2df38442721b?auto=format&fit=crop&w=400&q=80' },
  { id: 'p14', cat: 'beer', style: 'Lager',  name: 'Полтавське Поле',     abv: 5.0, ibu: 24, price: 100, vol: '0.5 л',  color: '#E0B05C', tagline: 'Пілснер з місцевого ячменю.',
    notes: 'Сухий, зерновий, хмельовий.', pair: 'Ковбаски, смажена риба.', origin: 'Крафтова пивоварня',
    image: 'https://images.unsplash.com/photo-1565539383096-875303015bd2?auto=format&fit=crop&w=400&q=80' },
  { id: 'p15', cat: 'beer', style: 'Sour',   name: 'Гранатовий Дим',      abv: 5.8, ibu: 10, price: 175, vol: '0.33 л', color: '#962F3C', tagline: 'Сауер з гранатом і димним солодом.',
    notes: 'Гранат, дим, кисло-солодкий баланс.', pair: 'Качка, дичина.', origin: 'Крафтова пивоварня',
    image: 'https://images.unsplash.com/photo-1579065436839-f2bb127c5606?auto=format&fit=crop&w=400&q=80' },
  { id: 'p16', cat: 'beer', style: 'Wheat',    name: 'Бузький Вітер',     abv: 5.3, ibu: 56, price: 197, vol: '0.5 л', color: '#6B4423', tagline: 'Обраний сорт №16. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 16.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://plus.unsplash.com/premium_photo-1695285406175-c3b866e96091?auto=format&fit=crop&w=400&q=80' },
  { id: 'p17', cat: 'beer', style: 'Sour',    name: 'Лавровий Місяць',     abv: 5.6, ibu: 59, price: 204, vol: '0.5 л', color: '#8B5A2B', tagline: 'Обраний сорт №17. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 17.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=400&q=80' },
  { id: 'p18', cat: 'beer', style: 'Porter',    name: 'Степова Далечінь',     abv: 6, ibu: 62, price: 211, vol: '0.33 л', color: '#5D4E37', tagline: 'Обраний сорт №18. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 18.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1566633806327-68e152aaf26d?auto=format&fit=crop&w=400&q=80' },
  { id: 'p19', cat: 'beer', style: 'IPA',    name: 'Дніпровський Бриз',     abv: 6.3, ibu: 65, price: 218, vol: '0.5 л', color: '#4A3728', tagline: 'Обраний сорт №19. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 19.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1615332579037-3c44b3660b53?auto=format&fit=crop&w=400&q=80' },
  { id: 'p20', cat: 'beer', style: 'Stout',    name: 'Мармуровий Зал',     abv: 6.7, ibu: 68, price: 85, vol: '0.5 л', color: '#7D5A50', tagline: 'Обраний сорт №20. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 20.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://plus.unsplash.com/premium_photo-1695285406062-6d33b6ab539c?auto=format&fit=crop&w=400&q=80' },
  { id: 'p21', cat: 'beer', style: 'Lager',    name: 'Янтарний Ранок',     abv: 7, ibu: 71, price: 92, vol: '0.33 л', color: '#9C6B4A', tagline: 'Обраний сорт №21. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 21.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1516458464372-eea4ab222b31?auto=format&fit=crop&w=400&q=80' },
  { id: 'p22', cat: 'beer', style: 'Wheat',    name: 'Карпатська Тінь',     abv: 7.4, ibu: 74, price: 99, vol: '0.5 л', color: '#3D2914', tagline: 'Обраний сорт №22. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 22.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1630446070374-df1ec648ac65?auto=format&fit=crop&w=400&q=80' },
  { id: 'p23', cat: 'beer', style: 'Sour',    name: 'Поліська Ніч',     abv: 7.7, ibu: 77, price: 106, vol: '0.5 л', color: '#B87333', tagline: 'Обраний сорт №23. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 23.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1546622891-02c72c1537b6?auto=format&fit=crop&w=400&q=80' },
  { id: 'p24', cat: 'beer', style: 'Porter',    name: 'Золотий Колос',     abv: 8.1, ibu: 8, price: 113, vol: '0.33 л', color: '#704214', tagline: 'Обраний сорт №24. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 24.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://plus.unsplash.com/premium_photo-1695658863900-57ed9d7865be?auto=format&fit=crop&w=400&q=80' },
  { id: 'p25', cat: 'beer', style: 'IPA',    name: 'Мідний Горн',     abv: 8.4, ibu: 11, price: 120, vol: '0.5 л', color: '#5C4033', tagline: 'Обраний сорт №25. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 25.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1462664450306-25ad625a342b?auto=format&fit=crop&w=400&q=80' },
  { id: 'p26', cat: 'beer', style: 'Stout',    name: 'Срібний Ручай',     abv: 4.2, ibu: 14, price: 127, vol: '0.5 л', color: '#4E3629', tagline: 'Обраний сорт №26. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 26.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1595600566063-2863388012be?auto=format&fit=crop&w=400&q=80' },
  { id: 'p27', cat: 'beer', style: 'Lager',    name: 'Гранітний Берег',     abv: 4.6, ibu: 17, price: 134, vol: '0.33 л', color: '#6F4E37', tagline: 'Обраний сорт №27. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 27.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1584225065152-4a1454aa3d4e?auto=format&fit=crop&w=400&q=80' },
  { id: 'p28', cat: 'beer', style: 'Wheat',    name: 'Вогняний Ритм',     abv: 4.9, ibu: 20, price: 141, vol: '0.5 л', color: '#A0522D', tagline: 'Обраний сорт №28. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 28.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://plus.unsplash.com/premium_photo-1695558758852-2df38442721b?auto=format&fit=crop&w=400&q=80' },
  { id: 'p29', cat: 'beer', style: 'Sour',    name: 'Льодовий Шлях',     abv: 5.3, ibu: 23, price: 148, vol: '0.5 л', color: '#CD853F', tagline: 'Обраний сорт №29. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 29.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1565539383096-875303015bd2?auto=format&fit=crop&w=400&q=80' },
  { id: 'p30', cat: 'beer', style: 'Porter',    name: 'Сонячний Вал',     abv: 5.6, ibu: 26, price: 155, vol: '0.33 л', color: '#D2691E', tagline: 'Обраний сорт №30. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 30.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1579065436839-f2bb127c5606?auto=format&fit=crop&w=400&q=80' },
  { id: 'p31', cat: 'beer', style: 'IPA',    name: 'Травневий Дощ',     abv: 6, ibu: 29, price: 162, vol: '0.5 л', color: '#BC8F8F', tagline: 'Обраний сорт №31. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 31.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://plus.unsplash.com/premium_photo-1695285406175-c3b866e96091?auto=format&fit=crop&w=400&q=80' },
  { id: 'p32', cat: 'beer', style: 'Stout',    name: 'Жнивний Дим',     abv: 6.3, ibu: 32, price: 169, vol: '0.5 л', color: '#C19A6B', tagline: 'Обраний сорт №32. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 32.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=400&q=80' },
  { id: 'p33', cat: 'beer', style: 'Lager',    name: 'Осінній Сад',     abv: 6.7, ibu: 35, price: 176, vol: '0.33 л', color: '#987654', tagline: 'Обраний сорт №33. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 33.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1566633806327-68e152aaf26d?auto=format&fit=crop&w=400&q=80' },
  { id: 'p34', cat: 'beer', style: 'Wheat',    name: 'Зимовий Сад',     abv: 7, ibu: 38, price: 183, vol: '0.5 л', color: '#665233', tagline: 'Обраний сорт №34. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 34.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1615332579037-3c44b3660b53?auto=format&fit=crop&w=400&q=80' },
  { id: 'p35', cat: 'beer', style: 'Sour',    name: 'Весняний Рікошет',     abv: 7.4, ibu: 41, price: 190, vol: '0.5 л', color: '#8B7355', tagline: 'Обраний сорт №35. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 35.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://plus.unsplash.com/premium_photo-1695285406062-6d33b6ab539c?auto=format&fit=crop&w=400&q=80' },
  { id: 'p36', cat: 'beer', style: 'Porter',    name: 'Кришталева Хвиля',     abv: 7.7, ibu: 44, price: 197, vol: '0.33 л', color: '#5A4A3A', tagline: 'Обраний сорт №36. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 36.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1516458464372-eea4ab222b31?auto=format&fit=crop&w=400&q=80' },
  { id: 'p37', cat: 'beer', style: 'IPA',    name: 'Мідний Захід',     abv: 8.1, ibu: 47, price: 204, vol: '0.5 л', color: '#7B5543', tagline: 'Обраний сорт №37. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 37.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1630446070374-df1ec648ac65?auto=format&fit=crop&w=400&q=80' },
  { id: 'p38', cat: 'beer', style: 'Stout',    name: 'Східний Сигнал',     abv: 8.4, ibu: 50, price: 211, vol: '0.5 л', color: '#9D7A5C', tagline: 'Обраний сорт №38. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 38.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1546622891-02c72c1537b6?auto=format&fit=crop&w=400&q=80' },
  { id: 'p39', cat: 'beer', style: 'Lager',    name: 'Північний Вогонь',     abv: 4.2, ibu: 53, price: 218, vol: '0.33 л', color: '#4C3B2B', tagline: 'Обраний сорт №39. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 39.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://plus.unsplash.com/premium_photo-1695658863900-57ed9d7865be?auto=format&fit=crop&w=400&q=80' },
  { id: 'p40', cat: 'beer', style: 'Wheat',    name: 'Південний Спокій',     abv: 4.6, ibu: 56, price: 85, vol: '0.5 л', color: '#6E5845', tagline: 'Обраний сорт №40. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 40.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1462664450306-25ad625a342b?auto=format&fit=crop&w=400&q=80' },
  { id: 'p41', cat: 'beer', style: 'Sour',    name: 'Нічний Експрес',     abv: 4.9, ibu: 59, price: 92, vol: '0.5 л', color: '#8F6F4A', tagline: 'Обраний сорт №41. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 41.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1595600566063-2863388012be?auto=format&fit=crop&w=400&q=80' },
  { id: 'p42', cat: 'beer', style: 'Porter',    name: 'Ранкова Зоря',     abv: 5.3, ibu: 62, price: 99, vol: '0.33 л', color: '#5B4332', tagline: 'Обраний сорт №42. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 42.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1584225065152-4a1454aa3d4e?auto=format&fit=crop&w=400&q=80' },
  { id: 'p43', cat: 'beer', style: 'IPA',    name: 'Полуденний Затишок',     abv: 5.6, ibu: 65, price: 106, vol: '0.5 л', color: '#A67C52', tagline: 'Обраний сорт №43. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 43.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://plus.unsplash.com/premium_photo-1695558758852-2df38442721b?auto=format&fit=crop&w=400&q=80' },
  { id: 'p44', cat: 'beer', style: 'Stout',    name: 'Вечірній Дзвін',     abv: 6, ibu: 68, price: 113, vol: '0.5 л', color: '#6D4C41', tagline: 'Обраний сорт №44. Смак, який повертають знову.',
    notes: 'Баланс солоду й хмелю, свіжий аромат, приємний фініш — лінійка магазину, позиція 44.', pair: 'Білий сир, копчена риба, домашня ковбаска.', origin: 'Нікополь · Наше Пиво',
    image: 'https://images.unsplash.com/photo-1565539383096-875303015bd2?auto=format&fit=crop&w=400&q=80' },
  // Snacks
  { id: 's01', cat: 'snacks', style: 'Снеки', name: 'Сушена Щука',         abv: null, price: 220, vol: '120 г', color: '#C8A46D', tagline: 'Дніпровська щука холодного сушіння.',
    notes: 'Солона, пружна, тримається тижнями.', pair: 'Лагер, пілснер.', origin: 'Нікополь',
    image: 'https://images.unsplash.com/photo-1767290712220-2892948dcdd7?auto=format&fit=crop&w=400&q=80' },
  { id: 's02', cat: 'snacks', style: 'Снеки', name: 'Чіпси з Житнього',    abv: null, price: 75,  vol: '80 г',  color: '#D5B274', tagline: 'Житні крекери з розмарином.',
    notes: 'Хрусткі, з сіллю флер-де-сель.', pair: 'IPA, Stout.', origin: 'Нікополь',
    image: 'https://images.unsplash.com/photo-1640323391688-26f3cf082e30?auto=format&fit=crop&w=400&q=80' },
  { id: 's03', cat: 'snacks', style: 'Снеки', name: 'Вʼялена Яловичина',   abv: null, price: 340, vol: '100 г', color: '#6E3822', tagline: 'Чорний перець, коньяк, 21 день.',
    notes: 'Щільна, пряна, з димною нотою.', pair: 'Портер, стаут.', origin: 'Нікополь',
    image: 'https://images.unsplash.com/photo-1652209695374-7a91c243f12f?auto=format&fit=crop&w=400&q=80' },
  { id: 's04', cat: 'snacks', style: 'Снеки', name: 'Смажений Нут',        abv: null, price: 95,  vol: '150 г', color: '#C8964A', tagline: 'Смажений з паприкою і чебрецем.',
    notes: 'Хрусткий, пряний, легкий.', pair: 'Пшеничне, лагер.', origin: 'Нікополь',
    image: 'https://images.unsplash.com/photo-1776057302065-45780d0b7631?auto=format&fit=crop&w=400&q=80' },
  { id: 's05', cat: 'snacks', style: 'Снеки', name: 'Оливки з Гіркого',    abv: null, price: 180, vol: '200 г', color: '#4B5432', tagline: 'Мариновані на пиві «Димний Пілігрим».',
    notes: 'Пружні, з димом і цитроном.', pair: 'Сауер, IPA.', origin: 'Нікополь',
    image: 'https://images.unsplash.com/photo-1698775942613-3e9fc114b2a1?auto=format&fit=crop&w=400&q=80' },
  { id: 's06', cat: 'snacks', style: 'Снеки', name: 'Сирна Дошка «Трійка»', abv: null, price: 420, vol: '250 г', color: '#E6C77C', tagline: 'Три витримки: 3, 9, 18 місяців.',
    notes: 'Горіх, карамель, кристали тирозину.', pair: 'Стаут, портер.', origin: 'Нікополь',
    image: 'https://plus.unsplash.com/premium_photo-1726877105476-bb50ed874f25?auto=format&fit=crop&w=400&q=80' },
];

const STYLES = ['IPA', 'Stout', 'Lager', 'Wheat', 'Sour', 'Porter', 'Снеки'];

window.PRODUCTS = PRODUCTS;
window.STYLES = STYLES;
